### PR TITLE
Decode additional bit in insulin sensitivity

### PR DESCRIPTION
**Pull request by ecc1**

### CODE REVIEW

**Comment by ecc1** [comment]
This is an UNTESTED fix for https://github.com/openaps/decocare/issues/21

**Comment by scottleibrand** [comment]
Anyone available to test this?

**Comment by scottleibrand** [comment]
Anyone available to test this?  @tmecklem, @bender1061, @cjo20 ?

**Comment by scottleibrand** [comment]
@ecc1 do you know what range of sensitivities should work before and after this change?  Wondering if @kdisimone could test this one like she did #28

**Comment by ecc1** [comment]
Maximum correctly-decoded sensitivities should be 255 before the change, 511 after the change (but model 522 limits it to 400, and I think 523 limits it to 500)

**Comment by Kdisimone** [comment]
sure I could.  I have been doing the work around of installing the updated decocare...that's worked too  `easy_install -U decocare`


related https://github.com/openaps/decocare/issues/25

**Comment by scottleibrand** [comment]
Just pushed an ecc1-dev branch to make this easier to test.  If anyone else (@SebastienLussier @ceben80 @Missdazzle @PieterGit) could help test this one as well, please do.

**Comment by Kdisimone** [comment]
tested, works on 523

before fix
screen shot 2017-07-16 at 12 44 38 pm

after fix

screen shot 2017-07-16 at 12 51 49 pm

**Comment by Kdisimone** [comment]
btw, carb ratios fix is in there too...looks good

**Comment by Kdisimone** [comment]
And lastly, the 523 only allows up to 400 for isf in the bolus wizard settings.

**Comment by scottleibrand** [comment]
Anyone else want to test this, or should I go ahead and merge it to dev?

**Comment by Kdisimone** [comment]
@scottleibrand I'd merge it at this point.  I tested on a 723 as well and it worked great

**Comment by jcwarrior** [comment]
Tested on 754. Max pump ISF is 400 and decoding right after fix

**Pull request merged**
