### PR TITLE
create dev area post release

### PR DESCRIPTION
**Pull request by bewest**
Dev happens here.

### CODE REVIEW

**Comment by scottleibrand** [comment]
I'd like to do a release soon to incorporate #2 into master.  Also need to determine whether openaps etc. are pointing to this repo or bewest/decoding-carelink.

**Comment by scottleibrand** [comment]
Just updated quick-src.sh to use openaps/decocare instead of bewest/decoding-carelink: https://github.com/openaps/docs/commit/ab5bdf3988ab35f9616139cdfef6be85f4ef2eac

**Comment by scottleibrand** [comment]
How is the version used by openaps determined?  Is that dependent on which repo is used to publish the decocare package?  If so, looks like that (https://pypi.python.org/pypi/decocare) already points to https://github.com/openaps/decocare, so I think we're good to merge this and do a release there.

**Comment by scottleibrand** [comment]
@bewest should I have perms to try to do a release of decocare?

**Comment by bewest** [comment]
You have pypi account?
Lets schedule some time later to make sure everything happens smoothly.

**Comment by scottleibrand** [comment]
I do now: username scottleibrand.

When works well for you?

**Comment by bewest** [comment]
Been on vacation with family, returning Tuesday.  When using `pip` to manage python packages, it's very similar to the way `npm` works: the tool knows how to install directly from git repos, as well as from `pypi`.  First, it searches pypi, using the `install_requires` keyword specified in `setup.py`.  This relies on semantic versioning.  Secondly, `pip` can also take an actual URL of various kinds.  The modification from `npm` is that `pip` requires an additional "helper" prefix: https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support, which allows installing arbitrary `@dev` references.

**Pull request merged**
